name: libreoffice
version: 7.4.5.1
summary: LibreOffice is a free and open source office suite
description: LibreOffice is a free and open source office suite, developed by The Document Foundation. The LibreOffice suite comprises programs for word processing, the creation and editing of spreadsheets, slideshows, diagrams and drawings, working with databases, and composing mathematical formulae.
confinement: strict
grade: devel
base: core20
compression: lzo

passthrough:
  layout:
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/firebird:
      bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/firebird

parts:
    # Launchpad builders have a timeout for how long they are allowed to access
    # the internet (through a proxy) starting from the start of the build.
    # Since the libreoffice part takes a long time to build, we need to ensure
    # that it is the last one to build, so that all other parts have had a
    # chance to pull their build and stage packages before the proxy
    # authentication is revoked.

    libreoffice-patches:
        plugin: dump
        source: patches
        organize:
            '*' : patches/
        override-prime: ""

    libreoffice:
        after:
            - libreoffice-patches
            - libreoffice-wrapper
            - spellchecking
            - hyphenation
            - thesauri
            - jvm
            - gstreamer
            - yaru-icons
        plugin: autotools
        source: https://download.documentfoundation.org/libreoffice/src/7.4.5/libreoffice-7.4.5.1.tar.xz
        autotools-configure-parameters:
            - --disable-ccache
            - --disable-coinmp
            - --disable-dconf
            - --disable-evolution2
            - --disable-online-update
            - --enable-dbus
            - --enable-eot
            - --enable-ext-wiki-publisher
            - --enable-extension-integration
            - --enable-gstreamer-1-0
            - --enable-mergelibs
            - --enable-release-build
            - --enable-scripting-beanshell
            - --enable-scripting-javascript
            - --with-gdrive-client-id=424119844901-gee57209rkbo1rgula4i0arilvgv3lsf.apps.googleusercontent.com
            - --with-gdrive-client-secret=3h1DknIrVsq2wEhIuADVxQ3E
            - --with-system-firebird
            - --with-system-graphite
            - --with-system-harfbuzz
            - --with-system-icu
            - --with-system-jpeg
            - --with-system-libexttextcat
            - --with-system-openldap
            - --with-system-nss
            - --with-system-hsqldb
            - --with-hsqldb-jar=/usr/share/java/hsqldb1.8.0.jar
            - --with-theme='colibre sifr sifr_dark breeze breeze_dark elementary'
            - --with-vendor='Canonical, Ltd.'
            - --with-help
            - --without-doxygen
            - --with-lang='en-US af am ar as ast be bg bn br bs ca ca-valencia cs cy da de dz el en-GB en-ZA eo es et eu fa fi fr ga gd gl gu gug he hi hr hu id is it ja ka kk km kmr-Latn kn ko lt lv mk mn ml mr nb ne nl nn nr nso oc om or pa-IN pl pt pt-BR ro ru rw si sk sl sr sr-Latn ss st sv szl ta te tg th tn tr ts ug uk uz ve vi xh zh-CN zh-TW zu'
        build-packages:
            - quilt
            - ant
            - ant-optional
            - bison
            - build-essential
            - default-jdk
            - doxygen
            - firebird-dev
            - firebird3.0-server-core
            - flex
            - gdb
            - gettext
            - gperf
            - junit4
            - libarchive-zip-perl
            - libcups2-dev
            - libdbus-glib-1-dev
            - libexttextcat-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgirepository1.0-dev
            - libgl1-mesa-glx
            - libgraphite2-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libhsqldb1.8.0-java
            - libhyphen-dev
            - libice-dev
            - libicu-dev
            - libkrb5-dev
            - liblcms2-dev
            - libldap2-dev
            - libnspr4-dev
            - libnss3-dev
            - libpq-dev
            - libpython3-dev
            - librdf0-dev
            - libsm-dev
            - libsuitesparse-dev
            - libx11-dev
            - libxaw7-dev
            - libxext-dev
            - libxinerama-dev
            - libxkbfile-dev
            - libxml2
            - libxml2-dev
            - libxml2-utils
            - libxrandr-dev
            - libxrender-dev
            - libxslt1-dev
            - libxslt1.1
            - libxt-dev
            - libxtst-dev
            - maven-repo-helper
            - python3-dev
            - unzip
            - wget
            - x11proto-render-dev
            - xorg
            - xsltproc
            - zip
            - zlib1g-dev
        stage-packages:
            - firebird3.0-common
            - firebird3.0-server-core
            - libdbus-glib-1-2
            - libexttextcat-2.0-0
            - libfreetype6
            - libgl1-mesa-glx
            - libharfbuzz-icu0
            - libhsqldb1.8.0-java
            - libldap-2.4-2
            - libnspr4
            - libnss3
            - libpython3.9
            - libsm6
            - libxml2
            - libxslt1.1
            - libx11-6
            - libxext6
            - libxinerama1
            - libxrandr2
            - libxrender1
        override-build: |
            set -eux
            QUILT_PATCHES=$SNAPCRAFT_STAGE/patches quilt push -a
            snapcraftctl build
            srcdir=$PWD
            cd workdir/CustomTarget/sysui/share/libreoffice
            SRCDIR=$srcdir INSTDIR=$srcdir/instdir DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIXDIR=usr KDEMAINDIR=usr PKG_CONFIG=pkg-config ./create_tree.sh
            chmod a+x $SNAPCRAFT_PART_INSTALL/usr/share
            for app in base calc draw impress math startcenter writer
            do
                sed -i \
                    -e "s#Icon=libreoffice7.4-$app#Icon=/usr/share/icons/hicolor/256x256/apps/libreoffice7.4-$app.png#" \
                    -e "s#^Exec=libreoffice7.4 --\(.*\)#Exec=libreoffice.\1#g" \
                    $SNAPCRAFT_PART_INSTALL/usr/local/lib/libreoffice/share/xdg/$app.desktop
            done
        prime:
            - etc/firebird/
            - lib/libreoffice/*
            - -lib/libreoffice/help/af
            - -lib/libreoffice/help/am
            - -lib/libreoffice/help/ar
            - -lib/libreoffice/help/as
            - -lib/libreoffice/help/ast
            - -lib/libreoffice/help/be
            - -lib/libreoffice/help/bg
            - -lib/libreoffice/help/bn
            - -lib/libreoffice/help/br
            - -lib/libreoffice/help/bs
            - -lib/libreoffice/help/cy
            - -lib/libreoffice/help/en-ZA
            - -lib/libreoffice/help/eo
            - -lib/libreoffice/help/fa
            - -lib/libreoffice/help/ga
            - -lib/libreoffice/help/gd
            - -lib/libreoffice/help/gu
            - -lib/libreoffice/help/gug
            - -lib/libreoffice/help/he
            - -lib/libreoffice/help/hr
            - -lib/libreoffice/help/is
            - -lib/libreoffice/help/ka
            - -lib/libreoffice/help/kk
            - -lib/libreoffice/help/kmr-Latn
            - -lib/libreoffice/help/kn
            - -lib/libreoffice/help/lt
            - -lib/libreoffice/help/lv
            - -lib/libreoffice/help/mk
            - -lib/libreoffice/help/mn
            - -lib/libreoffice/help/ml
            - -lib/libreoffice/help/mr
            - -lib/libreoffice/help/nb
            - -lib/libreoffice/help/ne
            - -lib/libreoffice/help/nn
            - -lib/libreoffice/help/nr
            - -lib/libreoffice/help/nso
            - -lib/libreoffice/help/oc
            - -lib/libreoffice/help/or
            - -lib/libreoffice/help/pa-IN
            - -lib/libreoffice/help/ro
            - -lib/libreoffice/help/rw
            - -lib/libreoffice/help/si
            - -lib/libreoffice/help/sr
            - -lib/libreoffice/help/sr-Latn
            - -lib/libreoffice/help/ss
            - -lib/libreoffice/help/st
            - -lib/libreoffice/help/szl
            - -lib/libreoffice/help/ta
            - -lib/libreoffice/help/te
            - -lib/libreoffice/help/tg
            - -lib/libreoffice/help/th
            - -lib/libreoffice/help/tn
            - -lib/libreoffice/help/ts
            - -lib/libreoffice/help/ug
            - -lib/libreoffice/help/uk
            - -lib/libreoffice/help/uz
            - -lib/libreoffice/help/ve
            - -lib/libreoffice/help/xh
            - -lib/libreoffice/help/zu
            - -lib/libreoffice/share/fonts
            - usr/lib/*/lib*
            - -usr/lib/*/libgtk*
            - -usr/lib/*/libgdk*
            - -usr/lib/*/libcairo*
            - -usr/lib/*/libpango*
            - -usr/lib/*/libwayland*
            - usr/lib/*/firebird/
            - -usr/lib/*/firebird/*/databases.conf
            - -usr/lib/*/firebird/*/fbtrace.conf
            - usr/lib/*/mesa/lib*
            - usr/share/icons/hicolor/256x256/apps/*
            - usr/share/java/
            - usr/sbin/*
        organize:
            usr/local/lib/libreoffice/ : lib/libreoffice/

    libreoffice-wrapper:
        plugin: dump
        source: .
        prime:
            - libreoffice.wrapper
            - javasettings.py
            - filebug.py
            - data-dir/*
            - config/*

    spellchecking:
        plugin: nil
        stage-packages:
            - hunspell-af
            - hunspell-bg
            - hunspell-bn
            - hunspell-bs
            - hunspell-cs
            - hunspell-da
            - hunspell-de-de
            - hunspell-el
            - hunspell-en-au
            - hunspell-en-ca
            - hunspell-en-gb
            - hunspell-en-us
            - hunspell-en-za
            - hunspell-es
            - hunspell-fr-classical
            - hunspell-gd
            - hunspell-gl
            - hunspell-gl-es
            - hunspell-gu
            - hunspell-gug
            - hunspell-he
            - hunspell-hi
            - hunspell-hr
            - hunspell-hu
            - hunspell-id
            - hunspell-is
            - hunspell-it
            - hunspell-kmr
            - hunspell-lo
            - hunspell-lt
            - hunspell-ne
            - hunspell-no
            - hunspell-oc
            - hunspell-pl
            - hunspell-pt-br
            - hunspell-pt-pt
            - hunspell-ro
            - hunspell-ru
            - hunspell-si
            - hunspell-sk
            - hunspell-sl
            - hunspell-sr
            - hunspell-sv
            - hunspell-sv-se
            - hunspell-sw
            - hunspell-te
            - hunspell-th
            - hunspell-tr
            - hunspell-uk
            - hunspell-vi

    hyphenation:
        plugin: nil
        stage-packages:
            - hyphen-af
            - hyphen-bg
            - hyphen-ca
            - hyphen-cs
            - hyphen-da
            - hyphen-de
            - hyphen-el
            - hyphen-en-gb
            - hyphen-en-us
            - hyphen-es
            - hyphen-fr
            - hyphen-gl
            - hyphen-hr
            - hyphen-hu
            - hyphen-id
            - hyphen-is
            - hyphen-it
            - hyphen-lt
            - hyphen-nl
            - hyphen-no
            - hyphen-pt-br
            - hyphen-pt-pt
            - hyphen-ro
            - hyphen-sk
            - hyphen-sl
            - hyphen-sr
            - hyphen-sv
            - hyphen-uk
            - hyphen-zu

    thesauri:
        plugin: nil
        stage-packages:
            - mythes-ar
            - mythes-bg
            - mythes-ca
            - mythes-cs
            - mythes-da
            - mythes-en-au
            - mythes-en-us
            - mythes-es
            - mythes-fr
            - mythes-gl
            - mythes-gug
            - mythes-hu
            - mythes-id
            - mythes-is
            - mythes-it
            - mythes-lv
            - mythes-ne
            - mythes-no
            - mythes-pt-pt
            - mythes-ro
            - mythes-ru
            - mythes-sk
            - mythes-sl
            - mythes-sv
            - mythes-uk

    jvm:
        plugin: nil
        stage-packages:
            - openjdk-11-jre
            - openjdk-11-jre-headless
        prime:
            - -usr/share/doc
        override-prime: |
            snapcraftctl prime
            rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs

    gstreamer:
        # GStreamer packages needed for audio/video clip playback in office
        # documents. Libreoffice uses the gtksink element.
        plugin: nil
        stage-packages:
            - gstreamer1.0-gtk3
            - gstreamer1.0-libav
            - gstreamer1.0-plugins-bad
            - gstreamer1.0-plugins-base
            - gstreamer1.0-plugins-good
            - gstreamer1.0-pulseaudio
            - libaa1
            - libass9
            - libavcodec58
            - libavfilter7
            - libavformat58
            - libavresample4
            - libavutil56
            - libbluray2
            - libbs2b0
            - libbz2-1.0
            - libcairo-gobject2
            - libcrystalhd3
            - libcurl3-gnutls
            - libde265-0
            - libdv4
            - libfaad2
            - libffi7
            - libflac8
            - libflite1
            - libfribidi0
            - libglu1-mesa
            - libgme0
            - libgmp10
            - libgnutls30
            - libgomp1
            - libgpm2
            - libgsm1
            - libgstreamer-plugins-bad1.0-0
            - libgstreamer-plugins-base1.0-0
            - libgstreamer-plugins-good1.0-0
            - libgstreamer1.0-0
            - libhogweed5
            - libidn2-0
            - libmp3lame0
            - libmodplug1
            - libnettle7
            - libnuma1
            - libogg0
            - libopenal1
            - libopenal-data
            - libopencv-core4.2
            - libopencv-imgproc4.2
            - libopenjp2-7
            - libopus0
            - liborc-0.4-0
            - libp11-kit0
            - libpostproc55
            - librtmp1
            - libshine3
            - libslang2
            - libsnappy1v5
            - libsodium23
            - libsoup2.4-1
            - libsoxr0
            - libspeex1
            - libssh-gcrypt-4
            - libswresample3
            - libswscale5
            - libtasn1-6
            - libtbb2
            - libtheora0
            - libtwolame0
            - libunistring2
            - libv4l-0
            - libva2
            - libvorbis0a
            - libvpx6
            - libwavpack1
            - libwebp6
            - libx265-179
            - libxvidcore4
            - libzmq5
            - libzvbi0
            - zlib1g

    yaru-icons:
        plugin: nil
        source: https://github.com/ubuntu/libreoffice-style-yaru-fullcolor/archive/refs/tags/2022-09-04.tar.gz
        override-build: |
            set -eux
            cd $SNAPCRAFT_PART_BUILD
            ./build.sh --zip
            if [ ! -f dist/images_yaru.zip ]; then
                echo "Yaru icons are missing!";
                exit 1;
            fi
            mkdir -p  $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
            cp $SNAPCRAFT_PART_BUILD/dist/images_yaru.zip $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/config/
        build-packages:
            - unzip

    cleanup:
        after: [ libreoffice ]
        plugin: nil
        build-snaps:
            - core20
            - gnome-3-38-2004
            - gtk-common-themes
        override-prime: |
            set -eux
            cd /snap/core20/current
            find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
            cd /snap/gnome-3-38-2004/current
            find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
            cd /snap/gtk-common-themes/current
            find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/{} \;

            # Ensure we don't override key libs from the platform snap
            rm -rf $SNAPCRAFT_PRIME/usr/lib/*/lib{gtk,gdk,cairo,pango,wayland}*

apps:
    libreoffice:
        command: libreoffice.wrapper
        desktop: lib/libreoffice/share/xdg/startcenter.desktop
        extensions: &extensions
            - gnome-3-38
        environment: &environment
            TMPDIR: $XDG_RUNTIME_DIR
        plugs: &plugs
            - audio-playback
            - bluez
            - cups-control
            - desktop
            - gsettings
            - home
            - network
            - network-bind
            - opengl
            - pulseaudio
            - removable-media
            - screen-inhibit-control
            - unity7
    base:
        command: libreoffice.wrapper --base
        desktop: lib/libreoffice/share/xdg/base.desktop
        common-id: libreoffice-base.desktop
        extensions: *extensions
        environment: *environment
        plugs: *plugs
    calc:
        command: libreoffice.wrapper --calc
        desktop: lib/libreoffice/share/xdg/calc.desktop
        common-id: libreoffice-calc.desktop
        extensions: *extensions
        environment: *environment
        plugs: *plugs
    draw:
        command: libreoffice.wrapper --draw
        desktop: lib/libreoffice/share/xdg/draw.desktop
        common-id: libreoffice-draw.desktop
        extensions: *extensions
        environment: *environment
        plugs: *plugs
    impress:
        command: libreoffice.wrapper --impress
        desktop: lib/libreoffice/share/xdg/impress.desktop
        common-id: libreoffice-impress.desktop
        extensions: *extensions
        environment: *environment
        plugs: *plugs
    math:
        command: libreoffice.wrapper --math
        desktop: lib/libreoffice/share/xdg/math.desktop
        common-id: libreoffice-math.desktop
        extensions: *extensions
        environment: *environment
        plugs: *plugs
    writer:
        command: libreoffice.wrapper --writer
        desktop: lib/libreoffice/share/xdg/writer.desktop
        common-id: libreoffice-writer.desktop
        extensions: *extensions
        environment: *environment
        plugs: *plugs
    filebug:
        command: filebug.py
        environment: *environment
        plugs:
            - desktop
            - network
